/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mockup;

public class App {
    public static void main(String[] args) {
        Window window = new Window();
    }
}
