/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package mockup;

import mockup.game.Game;

public class App {
    public static void main(String[] args) {
        new Game();
    }
}
